apiVersion: apps/v1
kind: Deployment
metadata:
  name: davmcache
  labels:
    app: davmcache
spec:
  selector:
    matchLabels:
      app: davmcache
  replicas: 1
  template:
    metadata:
      labels:
        app: davmcache
    spec:
      containers:
      - name: vpromc
        image: memcached
        ports:
        - name: vpromc-port
          containerPort: 11211